name: Website Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-id: [lint]
    steps:
      - name: get the codes
        uses: ./.github/workflows/install.yml
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-id: [test]
    steps:
      - name: get the codes
        uses: ./.github/workflows/install.yml
      - name: Test code
        id: tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job-id: [build]
    steps:
      - name: get the codes
        uses: ./.github/workflows/install.yml
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: report something
        run: |
          echo "something went wrong"
