name: install the dependencies
on: workflow_call
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: get the codes
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
